### ISSUE TITLE
setValue is not working

### ISSUE THREAD

**Issue by pavelsust** [Mohammed-Alaa/RangeSeekBar#1]
when i set a value(int) from my java code it son't show my position in the seekbar. What ever i set value it always show in the first.
![device-2019-03-26-174457](https://user-images.githubusercontent.com/7562445/54994630-e9830780-4fee-11e9-9d5d-889270e32a0d.png)

**Comment by MohammedAlaaMorsi** [comment]
@paveltech Thanks for your interest , you can now check the new version it have the fix

**Comment by pavelsust** [comment]
i already did it you can check it  out.

**Comment by MohammedAlaaMorsi** [comment]
Solved in version [1.0.2](https://github.com/Mohammed-Alaa/RangeSeekBar/releases/tag/1.0.2)
