### ISSUE TITLE
Attribute for gap between minimum and maximim

### ISSUE THREAD

**Issue by subhechhu** [Mohammed-Alaa/RangeSeekBar#15]
Is there any attribute for the gap between the values? Like if I want to have at least a gap of 10 between the lower and higher value. I am sorry if I missed it by any chance

**Comment by MohammedAlaaMorsi** [comment]
unfortunately currently there isn't attribute for that ,hope to add it in future when having time

**Comment by subhechhu** [comment]
Thanks. Appreciate the clean library though.
