### ISSUE TITLE
it has only one value

### ISSUE THREAD

**Issue by MahmoudMabrok** [Mohammed-Alaa/RangeSeekBar#5]
- range seems to have two thumbs not only one

**Comment by MohammedAlaaMorsi** [comment]
Could you add more details about this issue, like in which api-version this happens and what the steps that leads to this ?

**Comment by persadaditya** [comment]
maybe this, could you build this lib have two thumbs. so it has two value or two circle.
that is range definition is

**Comment by MahmoudMabrok** [comment]
like @aphe25  said buid lib with 2 thumbs

**Comment by MohammedAlaaMorsi** [comment]
this is not the intended implementation of the library , possibly this may be implemented in the future as a new feature

**Comment by MahmoudMabrok** [comment]
This feature is a **core** one as name of library imply this.

**Comment by persadaditya** [comment]
looking forward for your update, is really nice lib...
please notify me if you have update

**Comment by persadaditya** [comment]
nice bro... @MohammedAlaaMorsi 
nice job, well done

**Comment by MohammedAlaaMorsi** [comment]
Hi @aphe25 , @MahmoudMabrok  , I have updated the library , you can check now , also if you find it useful , it will be nice if you give it a star

**Comment by MohammedAlaaMorsi** [comment]
Added on latest release version [1.0.6](https://github.com/MohammedAlaaMorsi/RangeSeekBar/releases/tag/1.0.6)
