### ISSUE TITLE
Not building in gradle

### ISSUE THREAD

**Issue by devkenante** [Mohammed-Alaa/RangeSeekBar#7]
implementation 'com.github.Mohammed-Alaa:RangeSeekBar:1.0.2'
this is not working update the lib

**Comment by MohammedAlaaMorsi** [comment]
Hi @devkenante  this is an old version of the library which now are not supported you can find the latest version in `README.md` file which is `implementation 'com.github.MohammedAlaaMorsi:RangeSeekBar:1.0.4'`
